profiles:
  default:
    duration: 26w
    pass_threshold: 66
    allowed_voters:
      teams:
        - cncf-toc
      exclude_team_maintainers: true
  1wk:
    duration: 1w
    pass_threshold: 66
    allowed_voters:
      teams:
        - cncf-toc
      exclude_team_maintainers: true