profiles:
  default:
    duration: 26w
    pass_threshold: 66
    periodic_status_check: "1 day"
    allowed_voters:
      teams:
        - cncf-toc-voters
      exclude_team_maintainers: true
    close_on_passing: true
    announcements:
      discussions:
        category: announcements
  1wk:
    duration: 1w
    pass_threshold: 66
    allowed_voters:
      teams:
        - cncf-toc-voters
      exclude_team_maintainers: true
    close_on_passing: true

