name: Project Health
description: Register a concern regarding project health and alignment
title: "[HEALTH]: "
labels: ["health"]
body:
- type: markdown
  attributes:
    value: |
      **Purpose of This Issue**

      This Project Health Issue has been filed to ascertain the current activity and health of the project so the TOC may identify the appropriate support and guidance for the project to return to an optimal state of health or determination of archival.

      It is intended to **initiate a public discussion to seek understanding** and define a path forward. Perceptions or commentary counter to this are not constructive for the project or the community. 

      Should maintainers have sensitive, confidential, or private factors and concerns that influence or affect the project, they are encouraged to contact the TOC directly through CNCF Staff, the private-toc mailing list, Slack, or email.
- type: input
  id: project
  attributes: 
    label: Project name
    description: Which project does this concern pertain to?
  validations:
    required: true
- type: input
  id: project-issue-link
  attributes:
    label: Project Issue Link
    description: Please provide a link to the issue filed in the project's repository that corresponds to this TOC tracking issue.
    placeholder: e.g., https://github.com/project/repo/issues/123
  validations:
    required: true
- type: textarea
  id: concern
  attributes:
    label: Concern
    description: Please describe the specific concern with links and references to information supporting or exemplifying the concern regarding this project's health and alignment.
    placeholder: Links to devstats, issues, PRs, slack messages, etc. are all helpful but require your context to assist the TOC in understanding the concern.
  validations:
    required: true
- type: textarea
  id: toc-tag
  attributes:
    label: Prior engagement
    description: To the best of your knowledge, has the TOC or the TAG for this project been engaged on this or related topics previosuly?
    placeholder: If so, provide the name, any links, presentations, or other supportive information.
  validations:
    required: false
- type: textarea
  id: addt-info
  attributes:
    label: Additional Information
    description: Please provide any additional information to assist the TOC in reaching out to the project to understand these concerns better.
  validations:
    required: false
- type: textarea
  id: archiving-checklist
  attributes:
    label: Archiving Checklist (If project is determined for archival)
    value: |
      Once a project has been identified as unhealthy and a decision has been made to archive it, the following steps should be completed.
      When the archiving process is initiated add the `archive` label and assign: caniszczyk, mrbobbytables, idvoretskyi, jeefy, castrojo

      ### Archiving Checklist
      - [ ] TOC vote to archive passed
      - [ ] Move project (logo) to archived in the [artwork repo](https://github.com/cncf/artwork)
      - [ ] Move project to archived on [landscape](https://github.com/cncf/landscape)
      - [ ] Remove maintainer list from [project-maintainers.csv](https://github.com/cncf/foundation/blob/main/project-maintainers.csv)
      - [ ] Remove from staff list of maintainer emails
      - [ ] Archive (lock) maintainers mailing list (groups.io)
      - [ ] Remove ML from maintainers@ mailing group (google groups)
      - [ ] Remove project (logo) from all slide decks (contact pr@cncf.io)
      - [ ] Remove project (logo) from event sites (contact events@cncf.io)
      - [ ] Notify DevEx team to remove from event Maintainer Project Opportunities
      - [ ] Remove from maintainers & project from service desk
      - [ ] Remove from CNCF store (reach out to staff or email store@cncf.io)
      - [ ] Archive DevStats data (open issue in [devstats repo](https://github.com/cncf/devstats/issues))
      - [ ] Archive project in LFX Insights (move to archive in PCC)
      - [ ] Remove from [CLOMonitor data](https://raw.githubusercontent.com/cncf/clomonitor/main/data/cncf.yaml)
  validations:
    required: false