=== KubeEdge CNCF Sandbox Project Proposal

*Name of Project:* KubeEdge

*Description:*

KubeEdge is an extended K8s infrastructure for IOT/Edge workload. It aims to resolve three major issues at edge computing: network reliability and bandwidth between cloud and edge, resource constraint at edge, large scalability requirement.
It is an open-source system extending native containerized application orchestration and device management to hosts at the Edge. It is built upon Kubernetes and provides core infrastructure support for networking, application deployment and metadata synchronization between cloud and edge.
It also supports MQTT and allows developers to author custom logic and enable resource constrained device communication at the Edge

It is a general kubernetes infrastructure 

Here are some key advantages of KubeEdge:

* **Edge Computing:** With business logic running at the Edge, much larger volumes of data can be secured & processed locally where the data is produced. Edge nodes can run autonomously which effectively reduces the network bandwidth requirements and consumptions between Edge and Cloud. With data processed at the Edge, the responsiveness is increased dramatically and data privacy is protected.
* **Simplified development:** Developers can write regular http or mqtt based applications, containerize them, and run them anywhere - either at the Edge or in the Cloud - whichever is more appropriate.
* **Kubernetes-native support:** With KubeEdge, users can orchestrate apps, manage devices and monitor app and device status on Edge nodes just like a traditional Kubernetes cluster in the Cloud. Locations of edge nodes are transparent to customers.
* **Abundant applications:** It is easy to get and deploy existing complicated machine learning, image recognition, event processing and other high level applications to the Edge.

KubeEdge consists of below major components:

**In Cloud-Core:**

1. **EdgeController:** An extended kubernetes controller which manages edge nodes and pods metadata so that the data can be targeted to a specific edge node.
2. **CloudHub:** A web socket server responsible for watching changes at the cloud side, caching and sending messages to EdgeHub.

**In Edge-Core:**

1. **EdgeHub**: A web socket client for CloudHub's websocket server responsible for sending/receiving messages of/for all edge components to/from Cloud.

2. **Edged:**: An agent that runs on edge nodes and manages containerized applications.

3. **MetaManager:** the message processor between edged and edgehub. It is also responsible for storing/retrieving metadata to/from a lightweight database (SQLite).

4. **DeviceTwin:** The module responsible for storing device status and syncing device status to the cloud. It also provides query interfaces for applications.

5. **EventBus:** A MQTT client to interact with MQTT servers (mosquitto), offering publish and subscribe capabilities to other components.
**Statement on alignment with CNCF mission:**


*Roadmap:*

KubeEdge plans to support more advanced features which are useful in edge scenarios. Some of them are as follows:

1) Device management via CRD's
2) East-West communication
3) Multiple device protocol support (i.e Bluetooth, Zigbee, etc)
4) Data management
5) Monitoring & Alerting

*Sponsors from TOC:* 

*Preferred maturity level:* Sandbox

*License:* Apache License v2.0

*Source control:* GitHub (https://github.com/kubeedge/kubeedge)

*External Dependencies:* See https://github.com/kubeedge/kubeedge/blob/master/external-dependency.md[external-dependency.md] file.

*Initial Committers:* See https://github.com/kubeedge/kubeedge/blob/master/MAINTAINERS[MAINTAINERS] file.

*Founding Maintainers:*

 *  (Huawei)

*Additional Maintainers:*

 *  (Ebay China)

*Infrastructure requests (CI / CNCF Cluster):*

_Development needs:_

We currently use Travis CI, but we may want to use CNCF resources to deploy jenkis for node e2e test.

_Production needs:_

none

*Communication Channels:*

 * Slack: https://kubeedge.slack.com
 * Mailing List: https://groups.google.com/forum/#!forum/kubeedge (current), https://lists.cncf.io/g/cncf-kubeedge (proposed)
 * Issue tracker: https://github.com/kubeedge/kubeedge/issues

*Website:* https://kubeedge.io

*Release methodology and mechanics:*

We set the version rule of Dragonfly on the basis of SemVer which has a version number of MAJOR.MINOR.PATCH. Currently we do feature release 4-5 times per year(all with minor releases). Before every minor release, we plan to tag several RC releases to invite community developers to fully test them. In addition, all the code commits to Dragonfly project must add essential tests to cover the feature or code change. 

*Social media accounts:*

 * Twitter: https://twitter.com/KubeEdge

*Existing sponsorship:* Huawei

*Community size:*

https://github.com/kubeedge/kubeedge/stargazers[400+ stars]

https://github.com/kubeedge/kubeedge/network/members[100+ forks]

3 full-time engineers

https://github.com/kubeedge/kubeedge/graphs/contributors[30+ contributors]
