=== KubeInvaders CNCF Sandbox Project Proposal

*Name of Project:* KubeInvaders

*Description:*

KubeInvaders is a gamified chaos engineering tool for Kubernetes. It is like Space Invaders but the aliens are PODs.
It is very lightweight but I would like add some functionalities in order to transform KubeInvaders in an useful and interactive chaos engineering and monitoring tool.

Users can deploy KubeInvaders on Kubernetes via Helm charts.

KubeInvaders use cases:

* Test how resilient Kubernetes clusters are on unexpected pod deletion.
* Collect metrics like pod restart time.
* Tune readiness probes.

**Statement on alignment with CNCF mission:**

KubeInvaders is well-aligned with the CNCF's mission because allow developers to interact with Kubernetes clusters and test quickly the performance of pods.

It will be integrated with Prometheus.

*Roadmap:*

The project uses GitHub issues.

This is the roadmap:

1. Integrate KubeInvaders with Prometheus
2. Extend KubeInvaders to test not only pods but also: nodes, networking, disk i/o, cpu, memory.

*Sponsors from TOC:* Nobody for now...

*Preferred maturity level:* Sandbox

*License:* Apache License 2.0 

*Source control:* GitHub https://github.com/lucky-sideburn/KubeInvaders

*Maintainers:*

 * Eugenio Marzo (Sourcesense)

*Infrastructure requests (CI / CNCF Cluster):* none

We currently use test and build KubeInvaders on a Kimsufi physical server. We use Jenkins for CI/CD and Openshift and Kubernetes as target cluster.

*Communication Channels:*

 * Issue tracker: https://github.com/lucky-sideburn/KubeInvaders/issues

*Social media accounts:*

 * Twitte: https://twitter.com/luckysideburn

*Community size:*

500+ stars

6 contributors
