name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          days-before-stale: 60
          days-before-close: 14
          stale-issue-message: 'This issue will be closed due to inactivity. If this is still a valid issue, please comment or label triage appropriately.'
          stale-pr-message: 'This PR will be closed due to inactivity. If this is still a valid PR, please comment.'
          only-pr-labels: 'wontfix'
          exempt-issue-labels: 'project onboarding,enhancement'