%% This is the source for flowchart diagram
%% See: https://mermaidjs.github.io/#/flowchart
%% setup: `yarn install`  (in this directory)
%% regenerate diagram: `npm run diagram`
%% or use [mermaid live editor](https://mermaidjs.github.io/mermaid-live-editor)

graph TD
  New{New to CNCF?} --> |yes| Engage[Get Involved]
  subgraph Engage with CNCF Community 
    Engage --> |useful? used?| Projects
    Engage --> |present| SIG
    Engage --> |volunteer| SIG
  end
  New{New to CNCF?} --> |no| SIG

  SIG --> Champion{Champion?}
  Champion --> |no with feedback| Reject
  Champion --> |yes| DD{Due Dilligence}
  DD --> |open issues| Reject
  DD --> TOC1{TOC Presentation}
  TOC1 --> |unresolved concerns| Reject
  TOC1 --> PR{Proposal Pull Request}
  PR --> |feedback addressed| Vote{TOC Vote}
  PR --> |unresolved feedback| Reject
  Vote --> Accept
  Vote --> Reject

  subgraph project internal
    Reject[Questions or Concerns] --> |iterate| SIG
    Reject --> Bye[Step Back]

  end





